### ISSUE TITLE
[Feature Request] load from Gamecard SD 

### ISSUE THREAD

**Issue by causticglass** [profi200/open_agb_firm#106]
I just had a quick question about your open agb firm project. I understand you can load roms and saves from the SD card and any file you choose, but is it possible (or will it be possible) to be able to pull games from an SD card through the 3ds card slot? In a manner that twilightmenu can access a flashcards SD storage to browse files? Simply out of curiosity and as a way to expand storage options after backing up GBA games on a DS lite.

**Comment by profi200** [comment]
Can? Definitely but it's a lot of work for little gain. The whole DLDI stuff that makes this possible in DS mode does not work in 3DS mode so i would have to implement this for every single DS flashcard in existence.
