### ISSUE TITLE
Error while booting open_agb_firm

### ISSUE THREAD

**Issue by crystalstorm466** [profi200/open_agb_firm#113]
Model: New 3DS XL (US)

When ever I load a rom (currently only tested Pokemon Sapphire) the system would display two error messages and hang.

The two error messages are in order:
`Could not access gba_db.bin! Press any button to continue.`
`Errors: fatfs file not found.`

After these error messages the system would hang for an unspecified amount of time and would only show the gba splash screen then booting when I would press the power button. 

Picture is included below:
![20230517_005333](https://github.com/profi200/open_agb_firm/assets/78986447/cc9d6273-3f9c-4214-a292-3cb2efe136f9)

**Comment by profi200** [comment]
Either you didn't copy the included gba_db.bin to the SD card or your SD card filesystem is corrupt.

**Comment by profi200** [comment]
Extract the "3ds" folder inside the archive to the root of the SD card. If it asks if you want to merge folders/files then click yes.
