### ISSUE TITLE
is this still maintained?

### ISSUE THREAD

**Issue by GreatNateDev** [profi200/open_agb_firm#118]

**Comment by profi200** [comment]
Sort of. I didn't have much motivation to work on it in the recent months.

**Comment by GreatNateDev** [comment]
:( well if you ever do it again can't wait for cheat support

**Comment by GreatNateDev** [comment]
seems as though this is very active and definitely maintained loved that the dev got his motivation back ❤️

**Comment by ExtraBytez** [comment]
Bump! I'm still using this is this deprecated for another form or is this what everyone is still using?

**Comment by profi200** [comment]
There is no alternative as far as i'm aware. Currently there is more important stuff i invest time in which is why not much is happening.

**Comment by ExtraBytez** [comment]
> There is no alternative as far as i'm aware. Currently there is more important stuff i invest time in which is why not much is happening.

ok im glad you still acknowledged it. because a-lot of people will just leave a project to die without any communication.
