### ISSUE TITLE
Suggestions for Save issues.

### ISSUE THREAD

**Issue by RinMaru** [profi200/open_agb_firm#122]
I have a shit ton of free time and i want to help. I have no idea how program languages work but i was think. I could get a database of game ids and save types on a txt sheet and maybe it could be used as a way to tell what save types games use and be done with the issue altogether. Im not sure if such a list exists but if not id be more than happy to help

**Comment by beta215** [comment]
Check this issue, you'll get more information that will allow you to help the project!
https://github.com/profi200/open_agb_firm/issues/9
