### ISSUE TITLE
Savegame wont work in Emulator

### ISSUE THREAD

**Issue by Devine3DS** [profi200/open_agb_firm#129]
Hello,

I wanted to use the OpenAGBFirm Savegame of Pokemon Clover on an Emulator (the game is based on Emerald)
Ive tried to convert it using the EEprom fix tool but it wont work VBA or MGba wont load the Savegame... Idk what i should do next

**Comment by profi200** [comment]
Flash savegames don't need to be converted.

**Comment by Devine3DS** [comment]
Ive tried it normal but VBA wont load it. I got a .sav and a .ss0 
from open AGB

**Comment by profi200** [comment]
I'm not sure what you are doing wrong but oaf does not create .ss0 files and saves are located in "/3ds/open_agb_firm/saves".

**Comment by Devine3DS** [comment]
Omg sorry I used the wrong .sav file. Idk how it went that ... thank you so much!
