### ISSUE TITLE
Mother 3 deletes save file

### ISSUE THREAD

**Issue by epicwappy20** [profi200/open_agb_firm#137]
The fan translation of mother 3 was unable to save properly, and the .sav is for a chapter 2 save, even though i made it to chapter 4

**Comment by profi200** [comment]
Use a clean, verified ROM together with the patch file. A prepatched ROM will cause a fallback to inaccurate save type detection.

**Comment by epicwappy20** [comment]
Do I put the patch file in the same directory as the ROM, or am I just supposed to patch the rom.

**Comment by profi200** [comment]
Same directory as the ROM and same name (file extension differs).

**Comment by epicwappy20** [comment]
> Same directory as the ROM and same name (file extension differs).

I put the UPS in the same directory and it loaded the unpatched version

**Comment by epicwappy20** [comment]
The patch is only available in UPS format

**Comment by epicwappy20** [comment]
the files are: Mother3.gba(verified checksum) Mother3.sav, and Mother3.ups

**Comment by epicwappy20** [comment]
when booting the game in MGBA the patch loads

**Comment by epicwappy20** [comment]
Looks like I just needed to update open_agb_firm
