### ISSUE TITLE
Ms. Pac-Man - Maze Madness turns its own in-game audio settings to off on each boot

### ISSUE THREAD

**Issue by Dartz150** [profi200/open_agb_firm#143]
**Game**
Ms. Pac-Man - Maze Madness | BPCE, BPCP | USA, EUR

**Device Info**
Commit: 63e4422

Console: New3DS

Issue
The game disables audio in its own settings every time you load the game, even with previously saved data with sound enabled.

Screenshot taken from no$GBA just for reference, the issue doesn't happen on it.

![image](https://github.com/profi200/open_agb_firm/assets/42103728/ca25915b-0a29-438c-9c71-bb4a7f008829)

**Comment by Dartz150** [comment]
Turns out that I can only reproduce this in one specific 3DS console (my KTR model), the game works as intended in my other two 3DS consoles, an o3DS and a new3DSXL.

 So it could be an FCRAM issue. I'll reflow the chip later and report the result back, for the sake of FCRAM issues documentation.

**Comment by profi200** [comment]
Just to add what i already said in chat. I can't reproduce it with and without BIOS intro. Latest commit with the EUR version and fresh save file.

**Comment by Dartz150** [comment]
Turns out that this issue was caused by a faulty FCRAM, which also made my KTR n3DS to fail with other software in 3DS mode, leading to random crashes. I had to make a reflow job to the FCRAM chip and this fixed any issue completely, both on oaf and 3DS mode, which means that my FCRAM chip may had cracked solder balls.

Some pictures from the process:

![image](https://github.com/profi200/open_agb_firm/assets/42103728/fc5f2cb7-bd7c-4b2a-8840-c68074062485)

![image](https://github.com/profi200/open_agb_firm/assets/42103728/a9807529-8ce5-41fb-9aa7-23bd3a04ab3d)

![image](https://github.com/profi200/open_agb_firm/assets/42103728/96fc8f10-8195-4d29-a860-0bb95fd9bde6)

After cleaning the chip:

![image](https://github.com/profi200/open_agb_firm/assets/42103728/c22703e3-ab76-4a5a-8922-be28dcce3670)

The console fully working in both oaf (Ms. Pacman has sound again)
![image](https://github.com/profi200/open_agb_firm/assets/42103728/f04e9913-026f-4980-940a-69be6032278f)

![image](https://github.com/profi200/open_agb_firm/assets/42103728/216659c1-f4c9-4dbe-a7d3-e8b8db4aacc4)
