### ISSUE TITLE
Savegame differences across regions?

### ISSUE THREAD

**Issue by CobaltoSketcherino** [profi200/open_agb_firm#145]
The USA versions of _Klonoa: Empire of Dreams_ and _Klonoa 2: Dream Champ Tournament_ aren't saving correctly. The odd part is that the European release of _Empire_, and the Japanese release of _DCT_ save perfectly fine. Is there an inconsistency with save types across regions?
What should I do to help resolve this?

**Comment by profi200** [comment]
Make sure the ROM hashes match:
https://datomatic.no-intro.org/index.php?page=show_record&s=23&n=0112
https://datomatic.no-intro.org/index.php?page=show_record&s=23&n=1886

**Comment by CobaltoSketcherino** [comment]
I did some digging, even double-checking that I had everything sorted out ROM hash wise, turns out my gba_db.bin was the culprit. I think I must've gotten an old version of that somehow. Sorry for the trouble, and I absolutely LOVE the work you're doing!

**Comment by profi200** [comment]
Oof, i really should add a header with hash to the db format so it can be verified. I already saw issues like that coming.
