### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Tulip-0333** [profi200/open_agb_firm#156]
Add support to change the save data location, like if you wanted a GBARunner2 save to be the same save as AGB, without having to manually move and replace.

**Comment by Tulip-0333** [comment]
And add support for GBARunner2 saves period

**Comment by profi200** [comment]
First of all what kind of tone is that in the second post? You are not entitled to anything. I do this for free in my free time. Second, the save format is already compatible (except for EEPROM saves).

**Comment by Tulip-0333** [comment]
Sorry
