### ISSUE TITLE
Possibility of a screenshot feature?

### ISSUE THREAD

**Issue by Powerlated** [profi200/open_agb_firm#19]
I am wondering if the possibility exists of adding a screenshot feature to open_agb_firm. Not only could it be a cool feature, on-device screenshots would drastically lower difficulty for those wanting to run tests to reverse-engineer the GBA PPU.

**Comment by profi200** [comment]
This is basically already in but i removed it in the last build. It dumped the raw frame from LgyFb (basically the capture card) output. png is not easy to do and would increase code size significantly.

**Comment by Plecra** [comment]
Is there any need to use png? It be a lot easier to create a bmp file and just ignore compression

**Comment by profi200** [comment]
bmp should be doable.
