### ISSUE TITLE
Stuck at GBA Boot Screen with no nintendo logo

### ISSUE THREAD

**Issue by SebRock124** [profi200/open_agb_firm#195]
Title Says it all...

**Comment by Dartz150** [comment]
What are you trying to run? every GBA game on the library and most of the rom hacks should work fine (Except 64MB GBA video roms)

**Comment by SebRock124** [comment]
Ok nevermind... just found out it was because I was choosing the files with a broken name. There is a duplicate of all my files. It works now though. Just loaded up emerald fine.

**Comment by profi200** [comment]
Which duplicates? Is this yet another case where Mac OS creates meta data files that are hard to filter out?

**Comment by SebRock124** [comment]
Yes...

**Comment by profi200** [comment]
Try this nightly build. It should filter out these files.
https://github.com/profi200/open_agb_firm/actions/runs/10182033472

**Comment by SebRock124** [comment]
I just deleted the files in windows

**Comment by SebRock124** [comment]
But thank you for helping. Btw awesome project. I use the nightly build from when I submitted this and it works great!
