### ISSUE TITLE
3DS freezes if Power is pressed when LCDs are off

### ISSUE THREAD

**Issue by Nemris** [profi200/open_agb_firm#200]
### Overview
If the Power button is pressed or briefly held after the LCD backlight is turned off, the 3DS becomes unresponsive while the LED stays on, forcing the user to hold Power until the 3DS shuts down.

### Steps to reproduce
1. Launch a game;
2. Turn off LCD backlight with X-Left;
3. Press Power.

### System information
3DS Model: New3DS
OAF Version: 2024-07-30

**Comment by profi200** [comment]
Can reproduce. I will look into this later.

**Comment by profi200** [comment]
Should be fixed in commit edd43a6fcc7b8ffdd32516f250cc576603f8ec43.

See https://github.com/profi200/open_agb_firm/actions for a new nightly build with the fix.

**Comment by Nemris** [comment]
The fix is working.
