### ISSUE TITLE
Implement change ROM and last rom folder

### ISSUE THREAD

**Issue by redirectto** [profi200/open_agb_firm#21]
Is it possible for a newer version to be able to press a combination of buttons to select another game instead of having to turn off the console, also it would be nice if open_agb_firm remembered where it was the last folder you loaded a game

**Comment by profi200** [comment]
It's not possible to load a different ROM once GBA mode is running. It requires a reboot/poweroff. Remembering the last dir a ROM got loaded from is something i can add.

**Comment by foxsouns** [comment]
This issue should probably be closed: everything's been resolved.

**Comment by profi200** [comment]
Yeah, it didn't auto close yet because the commit is not in master yet.

**Comment by Dimensional** [comment]
Would a reboot that automatically takes you back into open_agb_firm be a plausible solution? No having to hold down start for Luma, or a button combination for FastBoot3DS?

**Comment by profi200** [comment]
That's pretty much the only way. Need to see how this can be done. But it's kinda low priority.
