### ISSUE TITLE
Install to SYSNAND

### ISSUE THREAD

**Issue by Mercredi31** [profi200/open_agb_firm#210]
Hello, i install open agb to SYSNAND and now, my 3DS is blocked to Open agb only. I don't have access to to luma or godemode, have you got a solution for me ?
Sorry for my English I'm French.

**Comment by profi200** [comment]
If you installed it to firm0/1 there is nothing i can do for you and you need ntrboot to unbrick the console. If you just overwrote boot.firm then place Luma3DS boot.firm on the SD card root.

**Comment by Mercredi31** [comment]
ok, i installed to firm0, thanks for your time, i ordered a flashcard.
For now, I play on my new GBA dual screen 😂😂
