### ISSUE TITLE
Latest update breaks per-game settings

### ISSUE THREAD

**Issue by TheGershon** [profi200/open_agb_firm#216]
Release 2024-12-24 breaks existing per-game .ini configs. Both color profiles and savetypes seem not to work, even after updating the strings to the new format. Perhaps it's something to do with the new useSavesFolder setting?

**Comment by profi200** [comment]
The configs need to be in the same folder as the save. This is behavior is hardcoded.

**Comment by TheGershon** [comment]
They are, I haven't changed their location since before the update.

**Comment by profi200** [comment]
Pretty sure i tested this and the per-game settings are still working for me. Obviously the ini files need to be updated to the new config format.

**Comment by TheGershon** [comment]
~~I have saves and per-game configs in `microsd:\3ds\open_agb_firm\saves`, for example `microsd:\3ds\open_agb_firm\saves\RomName.sav` and `microsd:\3ds\open_agb_firm\saves\RomName.txt`. The config looks like this:~~

I just noticed that all of my per-game config files were turned into txt files! No idea how or when that happened, very embarrassing. Closing!

**Comment by profi200** [comment]
Make sure to disable hiding file extensions in Windows. I don't understand why this is still the default for new Windows installs.

**Comment by Masamune3210** [comment]
The same reason all the other features that make no sense or are objectively hated are enabled by default, Microsoft thinking they know what people better than the people themselves do.
