### ISSUE TITLE
how to hide sdmc:\3ds\open_agb_firm

### ISSUE THREAD

**Issue by hozt81413** [profi200/open_agb_firm#36]
in "the homebrew launcher" ,open_agb_firm folder have not any program to run ,can hide "open_agb_firm"in "the homebrew launcher",thanks!

**Comment by profi200** [comment]
Unfortunately no unless hb-menu somehow allows hiding folders. Placing config and other stuff in this folder within /3ds was the best option for me because it prevents the root of the SD card getting filled with unnecessary files/folders.

**Comment by profi200** [comment]
Yes and no. Yes with some bootloaders you can boot into FIRM files from userland and no you canÄt directly boot GBA mode from within a userland app.

https://github.com/d0k3/A9NC
