### ISSUE TITLE
Limit of ROMs on a single folder is of 512

### ISSUE THREAD

**Issue by TheSandBoxMKG** [profi200/open_agb_firm#37]
I have a folder that has 543 ROMs, and the file browser seems to cap at maximum 512 listings,cutting out some ROMs.

Workaround is to divide the ROMs into more folders.

**Comment by profi200** [comment]
I limited this because it eats lots of RAM and i didn't think anyone has that many games in a single folder. I think i can bump that to 1024 but not much more.
