### ISSUE TITLE
Magical Vacation Softlock at Title Screen

### ISSUE THREAD

**Issue by Dartz150** [profi200/open_agb_firm#4]
Tested with every save type, every try resulted in a softlock that doesn't allow to press Start into the Title Screen to progress further into the game.

Tested in latest commit 391bc4d

**Comment by profi200** [comment]
Try the commit i just pushed? Unlikely it will do anything but might be worth a try.

Maybe asking the obvious but does this game work on original AGB_FIRM? Is the ROM a verified good dump?

**Comment by Dartz150** [comment]
Ok, I will try your fix asap with the new commit, thank you for your response! I'll be testing more games, so if anything comes up that is not related to save types (hopefully), I will post back here for advice. Thank you again!
