### ISSUE TITLE
[Request] Custom savegame folder

### ISSUE THREAD

**Issue by kprkpr** [profi200/open_agb_firm#50]
Hi!
There is any way to use different folder for savegames? Maybe in a config setting? 
This can be great to have less mess in folders (Or, for me for example, can share gPSP savefiles and open_agb_firm ones, that are compatible as is for can I see)
Thanks :)

**Comment by profi200** [comment]
This is something i thought of recently. Will add that later.

**Comment by profi200** [comment]
Forgot to close this. This has been solved in commit 247cb19cb5cb0722edea7fc1cdb0681743989541. It's included in the latest release i just published.
