### ISSUE TITLE
Support Gameboy Rom？

### ISSUE THREAD

**Issue by drhtree11097809** [profi200/open_agb_firm#52]
Support Gameboy Rom？

**Comment by profi200** [comment]
If you are asking for Super Game Boy support then no. There is no Game Boy (Color) support whatsoever. The hardware doesn't exist on 3DS.

**Comment by DraconicNEO** [comment]
> Support Gameboy Rom？

There's no Gameboy/Gameboy color hardware on the 3DS. Just use mGBA or Gameboy/Gameboy color Injects, they play Just fine.
