### ISSUE TITLE
Super mario advance working?

### ISSUE THREAD

**Issue by qamichele594-2** [profi200/open_agb_firm#55]
this is only an question

**Comment by beta215** [comment]
Any game that works in a DS/DS Lite's Slot-2 will work (except for games with built-in hardware like gyroscope, that isn't already available on the GBA). So, yes, Super Mario Advance works great.

**Comment by profi200** [comment]
Since this is already answered i'm gonna close it. Please remember issues are not for general questions. There is a `Discussions` tab above which is better suited for this.
