### ISSUE TITLE
cannot find open_agb_firm.firm file

### ISSUE THREAD

**Issue by SS1206** [profi200/open_agb_firm#80]
the set up says to put this file in luma but does not tell where the file is in the downloaded zip

**Comment by profi200** [comment]
It's right there in the root when opening the .7z/zip file.

**Comment by SS1206** [comment]
no it isn't...

**Comment by SS1206** [comment]
Ok, I figured it out for anyone who has this problem, thanks profi200 for helping me with this. I downloaded the wrong file. You need to download the 7zip file and not the zipped file. The ladder does not contain the .file file. That is why I was confused. The emulator works like a dream, thank you to the creators for making something better than the other 3ds emulator.
