### ISSUE TITLE
Audio cord problem

### ISSUE THREAD

**Issue by PiptonyZX** [profi200/open_agb_firm#85]
You shouldnt close it too soon because you said headset.  I didnt say headset.  I said audio cord which is male to male, which is for bluetooth speaker which include audio cord plug.

**Comment by profi200** [comment]
It's the same issue as #11. Usually it fails to detect 4 pin connectors for unknown reason. Can't rule out issues to detect 3 pin connectors as well.

Please continue in the issue i mentioned.
