### ISSUE TITLE
Can you please implement manual enable of headphone output?

### ISSUE THREAD

**Issue by kylxbn** [profi200/open_agb_firm#91]
Since there is an unsolved bug where some headphones are not recognized when plugged in and audio continues to play via the built-in speakers, can we please have a config setting (that will temporarily enable headphone output) or a key shortcut (that will toggle between speaker and headphone outputs)?

**Comment by profi200** [comment]
Fine, i'm gonna add an override. If you have one of these headphones with buttons try to hold the buttons for a few seconds.

**Comment by celloh123** [comment]
> Fine, i'm gonna add an override. If you have one of these headphones with buttons try to hold the buttons for a few seconds.

is there no other way? my headphones dont have buttons.

**Comment by profi200** [comment]
Other than modifying the code, no.

**Comment by profi200** [comment]
This is now implemented. See nightlies/actions tab.
